from __future__ import annotations


METRIC_CATALOG = [
    {
        "key": "revenue",
        "label": "Revenue",
        "category": "sales",
        "format": "currency",
        "polarity": "higher_is_better",
        "description": "Total order revenue captured in the selected period.",
        "formula_label": "sum(order revenue)",
        "business_question": "Are sales growing in the selected window?",
        "onboarding_required": True,
        "visible_by_default": True,
        "dashboard_slot": "headline",
        "sort_order": 10,
    },
    {
        "key": "net_profit",
        "label": "Net Profit",
        "category": "profit",
        "format": "currency",
        "polarity": "higher_is_better",
        "description": "Revenue left after fees, taxes, refunds, ads, COGS, and reimbursements.",
        "formula_label": "revenue - fees - taxes - refunds - ad_spend - cogs + reimbursements",
        "business_question": "How much money did the store actually keep?",
        "onboarding_required": True,
        "visible_by_default": True,
        "dashboard_slot": "headline",
        "sort_order": 20,
    },
    {
        "key": "profit_margin",
        "label": "Profit Margin",
        "category": "profit",
        "format": "percent",
        "polarity": "higher_is_better",
        "description": "Net profit as a percentage of revenue.",
        "formula_label": "net_profit / revenue * 100",
        "business_question": "Is growth translating into healthy contribution?",
        "warning_threshold": 12,
        "critical_threshold": 5,
        "onboarding_required": True,
        "visible_by_default": True,
        "dashboard_slot": "headline",
        "sort_order": 30,
    },
    {
        "key": "tacos",
        "label": "TACOS",
        "category": "ads",
        "format": "percent",
        "polarity": "lower_is_better",
        "description": "Total ad spend as a percentage of total revenue.",
        "formula_label": "ad_spend / revenue * 100",
        "business_question": "Are ads consuming too much of total sales?",
        "warning_threshold": 15,
        "critical_threshold": 25,
        "onboarding_required": True,
        "visible_by_default": True,
        "dashboard_slot": "headline",
        "sort_order": 40,
    },
    {
        "key": "acos",
        "label": "ACOS",
        "category": "ads",
        "format": "percent",
        "polarity": "lower_is_better",
        "description": "Ad spend as a percentage of ad-attributed sales.",
        "formula_label": "ad_spend / ad_sales * 100",
        "business_question": "Are campaigns efficient enough to keep scaling?",
        "warning_threshold": 30,
        "critical_threshold": 45,
        "onboarding_required": True,
        "visible_by_default": True,
        "dashboard_slot": "headline",
        "sort_order": 50,
    },
    {
        "key": "refund_rate",
        "label": "Refund Rate",
        "category": "operations",
        "format": "percent",
        "polarity": "lower_is_better",
        "description": "Refund amount as a percentage of revenue.",
        "formula_label": "refunds / revenue * 100",
        "business_question": "Are returns damaging profit quality?",
        "warning_threshold": 4,
        "critical_threshold": 8,
        "onboarding_required": True,
        "visible_by_default": True,
        "dashboard_slot": "headline",
        "sort_order": 60,
    },
    {
        "key": "ad_spend",
        "label": "Ad Spend",
        "category": "ads",
        "format": "currency",
        "polarity": "lower_is_better",
        "description": "Total advertising spend in the selected period.",
        "formula_label": "sum(ad spend)",
        "business_question": "How much is being reinvested into paid acquisition?",
        "visible_by_default": True,
        "dashboard_slot": "supporting",
        "sort_order": 70,
    },
    {
        "key": "roas",
        "label": "ROAS",
        "category": "ads",
        "format": "ratio",
        "polarity": "higher_is_better",
        "description": "Ad-attributed sales generated per unit of ad spend.",
        "formula_label": "ad_sales / ad_spend",
        "business_question": "How much revenue does each ad rupee generate?",
        "visible_by_default": True,
        "dashboard_slot": "supporting",
        "sort_order": 80,
    },
    {
        "key": "avg_order_value",
        "label": "AOV",
        "category": "sales",
        "format": "currency",
        "polarity": "higher_is_better",
        "description": "Average revenue per order.",
        "formula_label": "revenue / orders_count",
        "business_question": "Are pricing and bundles improving basket quality?",
        "visible_by_default": True,
        "dashboard_slot": "supporting",
        "sort_order": 90,
    },
    {
        "key": "orders_count",
        "label": "Orders",
        "category": "sales",
        "format": "number",
        "polarity": "higher_is_better",
        "description": "Number of order rows in the selected period.",
        "formula_label": "count(orders)",
        "business_question": "Is demand increasing or slowing down?",
        "visible_by_default": True,
        "dashboard_slot": "supporting",
        "sort_order": 100,
    },
    {
        "key": "units_sold",
        "label": "Units Sold",
        "category": "sales",
        "format": "number",
        "polarity": "higher_is_better",
        "description": "Total units sold in the selected period.",
        "formula_label": "sum(order units)",
        "business_question": "Which direction is unit velocity moving?",
        "visible_by_default": True,
        "dashboard_slot": "supporting",
        "sort_order": 110,
    },
    {
        "key": "cpc",
        "label": "CPC",
        "category": "ads",
        "format": "currency",
        "polarity": "lower_is_better",
        "description": "Average advertising cost per click.",
        "formula_label": "ad_spend / clicks",
        "business_question": "Are clicks getting more expensive?",
        "visible_by_default": True,
        "dashboard_slot": "supporting",
        "sort_order": 120,
    },
]


def get_metric_catalog() -> list[dict]:
    return sorted(METRIC_CATALOG, key=lambda item: item["sort_order"])
